site_name: A Google Chart Sample
dev_addr: 0.0.0.0:8080
site_description: Examples of integrating MkDocs with 3rd Party Libraries.
site_author: mihiko1116
site_url: http://michiko1116.github.io/mkdocs03/
repo_url: https://github.com/michiko1116/mkdocs03/
extra_javascript: []
extra_css: []
markdown_extensions: []
# git@github.com:michiko1116/mkdocs03.git
pages:
- ホーム: index.md
- 本サイトについて: about.md
- 自己紹介: profile.md
- ハロー: hello.md
- 'サンプル': 'samples/index.md'
